version: '3.8'
services:
  kafka-cluster:
    image: landoop/fast-data-dev:3.6
    environment:
      ADV_HOST: 172.0.0.1
    ports:
      - 2181:2181 #Zookeeper
      - 3030:3030 #Landoop UI
      - 8081-8083:8081-8083 #Rest Proxy, Schema Registry, Kafka Connect Ports
      - 9581-9585:9581-9585 # JMX Ports
      - 9092:9092 #Kafka broker