services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"

  kafka-cluster:
    image: landoop/fast-data-dev:cp3.3.0
    environment:
      ADV_HOST: 172.0.0.1
    ports:
      - 2181:2181 #Zookeeper
      - 3030:3030 #Landoop UI
      - 8081-8083:8081-8083 #Rest Proxy, Schema Registry, Kafka Connect Ports
      - 9581-9585:9581-9585 # JMX Ports
      - 9092:9092 #Kafka broker

volumes:
  mongodb: